function getNameById(id){
    switch(id){
        case "128": return "Pufferfish";
        case "129": return "Anchovy";
        case "130": return "Tuna";
        case "131": return "Sardine";
        case "132": return "Bream";
        case "136": return "Largemouth Bass";
        case "137": return "Smallmouth Bass";
        case "138": return "Rainbow Trout";
        case "139": return "Salmon";
        case "140": return "Walleye";
        case "141": return "Perch";
        case "142": return "Carp";
        case "143": return "Catfish";
        case "144": return "Pike";
        case "145": return "Sunfish";
        case "146": return "Red Mullet";
        case "147": return "Herring";
        case "148": return "Eel";
        case "149": return "Octopus";
        case "150": return "Red Snapper";
        case "151": return "Squid";
        case "154": return "Sea Cucumber";
        case "155": return "Super Cucumber";
        case "156": return "Ghostfish";
        case "158": return "Stonefish";
        case "159": return "Crimsonfish";
        case "160": return "Angler";
        case "161": return "Ice Pip";
        case "162": return "Lava Eel";
        case "163": return "Legend";
        case "164": return "Sandfish";
        case "165": return "Scorpion Carp";
        case "267": return "Flounder";
        case "269": return "Midnight Carp";
        case "372": return "Clam";
        case "682": return "Mutant Carp";
        case "698": return "Sturgeon";
        case "699": return "Tiger Trout";
        case "700": return "Bullhead";
        case "701": return "Tilapia";
        case "702": return "Chub";
        case "704": return "Dorado";
        case "705": return "Albacore";
        case "706": return "Shad";
        case "707": return "Lingcod";
        case "708": return "Halibut";
        case "715": return "Lobster";
        case "716": return "Crayfish";
        case "717": return "Crab";
        case "718": return "Cockle";
        case "719": return "Mussel";
        case "720": return "Shrimp";
        case "721": return "Snail";
        case "722": return "Periwinkle";
        case "723": return "Oyster";
        case "734": return "Woodskip";
        case "775": return "Glacierfish";
        case "795": return "Void Salmon";
        case "796": return "Slimejack";
        case "798": return "Midnight Squid";
        case "799": return "Spook Fish";
        case "800": return "Blobfish";
        case "836": return "Stingray";
        case "837": return "Lionfish";
        case "838": return "Blue Discus";
        case "898": return "Son of Crimsonfish";
        case "899": return "Ms. Angler";
        case "900": return "Legend II";
        case "901": return "Radioactive Carp";
        case "902": return "Glacierfish Jr.";
        case "Goby": return "Goby";

        default: return id;
    }
}